# Generated by Django 3.2.8 on 2022-03-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="role",),
        migrations.RemoveField(model_name="user", name="title",),
    ]
