# Generated by Django 3.2.8 on 2022-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("Visible", "Visible"),
                    ("Hidden", "Hidden"),
                    ("Archived", "Archived"),
                ],
                default="Visible",
                max_length=100,
            ),
        ),
    ]
